### ISSUE TITLE
Socket idle timeout problem

### ISSUE THREAD

**Issue by Andypro1** [LearnBoost/websocket.io#17]
The connection closes at precisely two minutes of idle time at the client.  I looked through the code and can't make heads or tails of where this is coming from.

tested on Chrome 15, Chrome 16, and Firefox 8.

**Comment by VanCoding** [comment]
I had the same problem. node-websocket-server by miksago has the same problem and it also has no code that closes the connection automatically after time. The only way that worked for me is to socket.setTimeout(0) all < 2min. in an interval

**Comment by Andypro1** [comment]
Would you mind posting some sample code for that?  Either with socket.io or node-websocket-server; either is fine with me.  I'm not sure if either exposes the socket object through the library.

**Comment by VanCoding** [comment]
I've created a fork of websocket.io and added some code to it that does what you want. It's just to give you an idea how you can do it.

You can find the fork here:
https://github.com/VanCoding/websocket.io

**Comment by Andypro1** [comment]
Perfect.  Seems to be working well thus far.  Thanks for your help!  Closing.
