### ISSUE TITLE
server.clients grows over time

### ISSUE THREAD

**Issue by nicokaiser** [LearnBoost/websocket.io#20]
In server.js you constantly push new clients to `self.clients`, and just set the array entry to `null` on close.

https://github.com/LearnBoost/websocket.io/blob/5251662a277ac17ac65eca9cad7d2ce433e20119/lib/server.js#L67

This leads to a constantly growing array which consists mostly of `null` (all disconnected clients). Can this be a memory problem over time?

**Comment by rauchg** [comment]
It would be a very minimal one.

**Comment by nicokaiser** [comment]
Ok, thanks for clarifying, I already thought something like this, but was not sure.
