### ISSUE TITLE
Leverage ws parsers

### ISSUE THREAD

**Issue by rauchg** [LearnBoost/websocket.io#23]

**Comment by nicokaiser** [comment]
Do you mean something like this? 

https://github.com/nicokaiser/websocket.io/commit/3ebc2c8280be69137fdcfa5fa1c7e4ad480f3766

(see https://github.com/nicokaiser/websocket.io/tree/wsparsers )

**Comment by rauchg** [comment]
Indeed!

**Comment by nicokaiser** [comment]
However it renders the parser tests useless, so I removed them. Then again, the ws parser is tested in the ws module itself...

**Comment by rauchg** [comment]
Yep that's good. websocket.io is an interface, so we should test the interface.

**Comment by nicokaiser** [comment]
(btw, I took most of the code from @einaros' socket.io fork)

**Comment by einaros** [comment]
That's exactly why I added the handleUpgrade() method in WebSocketServer back in january. :)
