### ISSUE TITLE
How to filter clients with the origin?

### ISSUE THREAD

**Issue by arunoda** [LearnBoost/websocket.io#44]
I need to only to allow some domains for my websocket server.
How to configure that with websocket.io?

**Comment by rauchg** [comment]
Great question

**Comment by arunoda** [comment]
BTW: I just figure it out origin header has no use at all
http://learnitcorrect.com/blog/websocket-is-great-but-not-the-origin-policy.html

**Comment by rauchg** [comment]
It does have an use, see the comment by @saurik. Of course anyone can create a new request with any `Origin` whatsoever from their terminal, but the key is can the website the user is visiting do it ?

**Comment by arunoda** [comment]
Yes. he is correct.
So how about a API like this?

``` javascript

var options = {
  allowOrigin: function(origin) {
     return true;
  }
};

var ws = require('websocket.io')
  , server = ws.listen(3000, null, options);

server.on('connection', function (socket) {
  socket.on('message', function () { });
  socket.on('close', function () { });
});
```

**Comment by rauchg** [comment]
Async maybe ?
And called `originCheck` ?

**Comment by arunoda** [comment]
Sounds good to me.
And this should be optional right?

``` javascript
var options = {
  originCheck: function(origin, confirm) {
     confirm(true);
  }
};

var ws = require('websocket.io')
  , server = ws.listen(3000, null, options);

server.on('connection', function (socket) {
  socket.on('message', function () { });
  socket.on('close', function () { });
});
```

**Comment by rauchg** [comment]
Correct. 

If falsy, accepts the origin.
If function, supplies the origin and callback.

**Comment by arunoda** [comment]
awesome.
