### ISSUE TITLE
Node version requirements

### ISSUE THREAD

**Issue by nicokaiser** [LearnBoost/websocket.io#5]
In package.json you specify "engines": { "node": ">= 0.5.0 < 0.7.0" }
Does WebSocket.IO require Node 0.6? It seems to run fine with Node 0.4.x...

**Comment by rauchg** [comment]
The tests run only on 0.6. I guess we should probably say > 0.4

**Comment by rauchg** [comment]
@einaros are you going to make easy-websocket work on 0.4 ?

**Comment by einaros** [comment]
Yes. Will be implemented today.
